name: CICD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Backend Dependencies
      run: npm install
      working-directory: backend

    - name: Install Frontend Dependencies
      run: npm install
      working-directory: frontend

    - name: Build Frontend
      run: npm run build
      working-directory: frontend

    - name: Prepare Deployment Package
      run: |
        mkdir -p build/public
        cp -r backend/* build/
        cp -r frontend/build/* build/public/
      shell: bash

    - name: Generate Deployment Package
      run: zip -r Document-view-docker.zip build

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: 'Document-view-docker'
        environment_name: 'Document-view-docker-env'
        version_label: 12345
        region: ap-south-1
        deployment_package: Document-view-docker.zip
